/* Generated By:JJTree: Do not edit this line. ASTEscapedDirective.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.apache.velocity.runtime.parser;

public
class ASTEscapedDirective extends SimpleNode {
  public ASTEscapedDirective(int id) {
    super(id);
  }

  public ASTEscapedDirective(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2158c6b2e5b1a703c3c62f0edcd1eb9c (do not edit this line) */
