/* Generated By:JJTree: Do not edit this line. ASTIntegerRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.apache.velocity.runtime.parser;

public
class ASTIntegerRange extends SimpleNode {
  public ASTIntegerRange(int id) {
    super(id);
  }

  public ASTIntegerRange(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d45589eb0cc5769fb8a06fce31cee4ac (do not edit this line) */
