/* Generated By:JJTree: Do not edit this line. ASTSubtractNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.apache.velocity.runtime.parser;

public
class ASTSubtractNode extends SimpleNode {
  public ASTSubtractNode(int id) {
    super(id);
  }

  public ASTSubtractNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0372dd871e971ef965e6c096a1ccd1b2 (do not edit this line) */
